# Generated by Django 5.1.2 on 2024-11-09 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_remove_inventoryitem_barcode_inventoryitem_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='category',
            field=models.CharField(choices=[('Dairy', 'Dairy Items'), ('Meat', 'Meat'), ('Fruits', 'Fruits')], default=0, max_length=50),
            preserve_default=False,
        ),
    ]
